services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: monitor-rio-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    networks:
      - monitor-rio-network

  # Serviço opcional para desenvolvimento com hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: monitor-rio-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8001:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8001
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    networks:
      - monitor-rio-network
    profiles:
      - dev

networks:
  monitor-rio-network:
    driver: bridge

volumes:
  database:
  storage:
  public:
